name: Test

run-name: Test (${{inputs.packages}})

on:
  push:

env:
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}

jobs:
  example_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install eyes-robotframework==5.12.4
      - run: robot test_propagation.robot
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.os}}
          path: "*"

  oracle_linux:
    runs-on: ubuntu-latest
    container: oraclelinux:7
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.9"
      - run: pip install eyes-robotframework==5.12.4
      - run: robot test_propagation.robot
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.os}}
          path: "*"

