name: Test

run-name: Test (${{inputs.packages}})

on:
  push:

env:
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}

jobs:
  example_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install robotframework==5.0.1 eyes-robotframework==5.12.4
      - run: robot test_propagation.robot
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.os}}
          path: "*"

  oracle_linux:
    runs-on: ubuntu-latest
    container: oraclelinux:7
    steps:
      - uses: actions/checkout@v3
      - run: |
          yum install -y gcc openssl-devel bzip2-devel libffi-devel zlib-devel make perl
          curl -OL https://ftp.openssl.org/source/openssl-1.1.1e.tar.gz
          tar xzf openssl-1.1.1e.tar.gz
          cd openssl-1.1.1e
          ./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic
          make install
          cd ..
          rm -rf openssl-1.1.1e
          curl -OL https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tgz 
          tar xzf Python-3.9.9.tgz
          cd Python-3.9.9
          ./configure --enable-optimizations 
          make altinstall
          cd ..
          rm -rf Python-3.9.9
          
          python3.9 -m pip install robotframework==5.0.1 eyes-robotframework==5.12.4
          python3.9 -m robot test_propagation.robot
      - uses: actions/upload-artifact@v3
        with:
          name: oracle
          path: "*"

