name: Test

run-name: Test (${{inputs.packages}})

on:
  push:

env:
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}

jobs:
  example_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install robotframework==5.0.1 eyes-robotframework==5.12.4
      - run: robot test_propagation.robot
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.os}}
          path: "*"

  oracle_linux:
    runs-on: ubuntu-latest
    container: oraclelinux:7
    steps:
      - uses: actions/checkout@v3
      - run: |
          yum install -y gcc openssl-devel bzip2-devel libffi-devel zlib-devel make unzip
          yum-config-manager --enable ol7_optional_latest
          curl -OL  https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
          yum -y localinstall google-chrome-stable_current_x86_64.rpm
          curl -OL https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.0/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          mv chromedriver-linux64/chromedriver /usr/local/bin/
          
          curl -OL https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tgz 
          tar xzf Python-3.9.9.tgz
          cd Python-3.9.9
          ./configure --enable-optimizations 
          make altinstall
          cd ..
          rm -rf Python-3.9.9
          
          python3.9 -m pip install "urllib3<2" robotframework==5.0.1 eyes-robotframework==5.12.4
          python3.9 -m robot test_propagation.robot
      - uses: actions/upload-artifact@v3
        with:
          name: oracle
          path: "*"

