name: Test

run-name: Test (${{inputs.packages}})

on:
  push:

env:
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}

jobs:
  example_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install robotframework==5.0.1 eyes-robotframework==5.12.4
      - run: robot test_propagation.robot
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.os}}
          path: "*"

  oracle_linux:
    runs-on: ubuntu-latest
    container: oraclelinux:7
    steps:
      - uses: actions/checkout@v3
      - run: |
          yum install -y oracle-softwarecollection-release-el7
          yum install -y rh-python38
          source /opt/rh/rh-python38/enable
          python3 -m pip install robotframework==5.0.1 eyes-robotframework==5.12.4
          python3 -m robot test_propagation.robot
      - uses: actions/upload-artifact@v3
        with:
          name: oracle
          path: "*"

